default["slurm"]["version"] = "14.03.8"
default["slurm"]["download_url"] = "http://www.schedmd.com/download/latest/slurm-#{node["slurm"]["version"]}.tar.bz2"
default["slurm"]["download_dir"] = "/tmp"
default["slurm"]["checksum"] = "ff1ed624553eedca4df172de6d4a61b8b22b5095ecfc725c3444e3926465c054"
#default["slurm"]["prefix"] = "/usr/local"
default["slurm"]["prefix"] = ""
default["slurm"]["sysconfdir"] = "#{node["slurm"]["prefix"]}/etc"
default["slurm"]["node_list"] = "node[001-010]"
default["slurm"]["role"] = "execute"
default["slurm"]["cluster_name"] = "slurm_cluster"

# TODO: Determine user and group information.
default["slurm"]["user"] = "slurm"
default["slurm"]["uid"] = "1002"
default["slurm"]["group"] = "slurm"
default["slurm"]["gid"] = "1001"
